# Generated by Django 3.1.7 on 2021-03-14 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='frontpage',
            field=models.BooleanField(default=False),
        ),
    ]
