# Generated by Django 3.1.7 on 2021-03-27 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_photo_frontpage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='slug',
            field=models.SlugField(blank=True, editable=False, max_length=200),
        ),
    ]
