# Generated by Django 3.1.7 on 2021-03-14 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_remove_contact_instagram'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='instagram',
            field=models.URLField(blank=True),
        ),
    ]
